--STORED PROCEDURES--
--1. INSERT--
    --DEPARTMENT--
    CREATE PROC PR_DEPARTMENT_INSERT
	   @DEPARTMENT_ID   INT,
	   @DEPARTMENT_NAME VARCHAR(100)
     AS
	 BEGIN
	   INSERT INTO DEPARTMENT
	   (
	     DEPARTMENT_ID,DEPARTMENT_NAME
	   )
	   VALUES
	   (
	      @DEPARTMENT_ID,
		  @DEPARTMENT_NAME
		)
END

EXEC PR_DEPARTMENT_INSERT 1,ADMIN
EXEC PR_DEPARTMENT_INSERT 2,IT
EXEC PR_DEPARTMENT_INSERT 3,HR
EXEC PR_DEPARTMENT_INSERT 4,ACCOUNT

SELECT * FROM DEPARTMENT

   --DESIGNATION--
CREATE PROC PR_DESIGNATION_INSERT
  @DESIGNATION_ID   INT,
  @DESIGNATION_NAME VARCHAR(100)
AS
BEGIN
   INSERT INTO DESIGNATION
   (
     DESIGNATION_ID,DESIGNATION_NAME
   )
   VALUES
   (
    @DESIGNATION_ID,@DESIGNATION_NAME
   )
END

EXEC  PR_DESIGNATION_INSERT 11,JOBBER
EXEC  PR_DESIGNATION_INSERT 12,WELDER
EXEC  PR_DESIGNATION_INSERT 13,CLERK
EXEC  PR_DESIGNATION_INSERT 14,MANAGER
EXEC  PR_DESIGNATION_INSERT 15,CEO

SELECT * FROM DESIGNATION

  --PERSON--
CREATE PROC PR_PERSON_INSERT
  @FIRST_NAME     VARCHAR(100),
  @LAST_NAME      VARCHAR(100),
  @SALARY         DECIMAL(8,2),
  @JOINING_DATE   DATETIME,
  @DEPARTMENT_ID  INT,
  @DESIGNATION_ID INT
AS
BEGIN
    INSERT INTO PERSON
	(
	 FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT_ID,DESIGNATION_ID
	)
	VALUES
	(
	 @FIRST_NAME,    
	 @LAST_NAME ,    
	 @SALARY ,       
	 @JOINING_DATE  ,
	 @DEPARTMENT_ID ,
	 @DESIGNATION_ID
	)
END
EXEC PR_PERSON_INSERT 'RAHUL','ANSHU',56000.00,'1990-01-01',1,12
EXEC PR_PERSON_INSERT 'HARDIK','HINSU',18000.00,'1990-09-25',2,11
EXEC PR_PERSON_INSERT 'BHAVIN','KAMANI',25000.00,'1991-05-14',NULL,11
EXEC PR_PERSON_INSERT 'BHOOMI','PATEL',39000.00,'2014-02-20',1,13
EXEC PR_PERSON_INSERT 'ROHIT','RAJGOR',17000.00,'1990-07-23',2,15
EXEC PR_PERSON_INSERT 'PRIYA','MEHTA',25000.00,'1990-10-18',2,NULL
EXEC PR_PERSON_INSERT 'NEHA','TRIVEDI',18000.00,'2014-02-20',3,15
 
 SELECT * FROM PERSON

--UPDATE--
 --DEPARTMENT--
 CREATE PROC PR_DEPARTMENT_UPDATE
	   @DEPARTMENT_ID   INT,
	   @DEPARTMENT_NAME VARCHAR(100)
AS
BEGIN
 UPDATE DEPARTMENT
 SET
    DEPARTMENT_ID  = @DEPARTMENT_ID,
	DEPARTMENT_NAME= @DEPARTMENT_NAME
  WHERE DEPARTMENT_ID  = @DEPARTMENT_ID
END
EXEC PR_DEPARTMENT_UPDATE 1,ADMIN1

   --DESIGNATION--
CREATE PROC PR_DESIGNATION_UPDATE
  @DESIGNATION_ID   INT,
  @DESIGNATION_NAME VARCHAR(100)
AS
BEGIN
  UPDATE DESIGNATION
  SET
    DESIGNATION_ID=   @DESIGNATION_ID,
    DESIGNATION_NAME=@DESIGNATION_NAME
	WHERE  DESIGNATION_ID=   @DESIGNATION_ID
END
EXEC PR_DESIGNATION_UPDATE 11,JOBBER1

  --PERSON--
CREATE PROC PR_PERSON_UPDATE
  @WORKER_ID      INT,
  @FIRST_NAME     VARCHAR(100),
  @LAST_NAME      VARCHAR(100),
  @SALARY         DECIMAL(8,2),
  @JOINING_DATE   DATETIME,
  @DEPARTMENT_ID  INT,
  @DESIGNATION_ID INT
AS
BEGIN
  UPDATE PERSON
  SET
     FIRST_NAME = @FIRST_NAME  ,
	 LAST_NAME   =  @LAST_NAME,
	 SALARY     =   @SALARY,
	 JOINING_DATE = @JOINING_DATE,
	 DEPARTMENT_ID =@DEPARTMENT_ID,
	 DESIGNATION_ID=@DESIGNATION_ID
  WHERE WORKER_ID  =@WORKER_ID
END

EXEC PR_PERSON_UPDATE 101,'RAHUL_1','ANSHU_1',57000.00,'1990-1-1',1,12

--DELETE--
  --DEPARTMENT--
CREATE PROC PR_DEPARTMENT_DELETE
       @DEPARTMENT_ID   INT
AS
BEGIN
  DELETE FROM DEPARTMENT
  WHERE DEPARTMENT_ID=@DEPARTMENT_ID
END
EXEC PR_DEPARTMENT_DELETE 4

--DESIGNATION--
CREATE PROC PR_DESIGNATION_DELETE
  @DESIGNATION_ID   INT
AS
BEGIN
    DELETE FROM DESIGNATION
	WHERE DESIGNATION_ID=@DESIGNATION_ID
END
EXEC PR_DESIGNATION_DELETE 14

--PERSON--
CREATE PROC PR_PERSON_DELETE
  @WORKER_ID      INT
AS
BEGIN
    DELETE FROM PERSON
	WHERE WORKER_ID=@WORKER_ID
END
EXEC PR_PERSON_DELETE 101

--2. all tables selectALL
CREATE PROC PR_DEPARTMENT_SELECTALL
AS
BEGIN
   SELECT * FROM DEPARTMENT
END

EXEC PR_DEPARTMENT_SELECTALL
  

CREATE PROC PR_DESIGNARION_SELECTALL
AS
BEGIN
   SELECT * FROM DESIGNATION
END

EXEC PR_DESIGNARION_SELECTALL

CREATE PROC PR_PERSON_SELECTALL
AS
BEGIN
   SELECT 
     PERSON.WORKER_ID,
	 PERSON.FIRST_NAME,
	 PERSON.LAST_NAME,
	 PERSON.SALARY,
	 PERSON.JOINING_DATE,
	 DEPARTMENT.DEPARTMENT_NAME,
	 DESIGNATION.DESIGNATION_NAME
	 FROM PERSON INNER JOIN DEPARTMENT
	 ON
	 PERSON.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID
	 INNER JOIN DESIGNATION
	 ON
	 PERSON.DESIGNATION_ID=DESIGNATION.DESIGNATION_ID
END

EXEC PR_PERSON_SELECTALL

--3.ALL TABLES SELECT_PK

CREATE PROC PR_DEPARTMENT_SELECTPK
   @DEPARTMENT_ID INT
AS
BEGIN
   SELECT * FROM DEPARTMENT
   WHERE DEPARTMENT_ID=@DEPARTMENT_ID;
END

EXEC PR_DEPARTMENT_SELECTPK 2

CREATE PROC PR_DESIGNATION_SELECTPK
   @DESIGNATION_ID INT
AS
BEGIN
   SELECT * FROM DESIGNATION
   WHERE DESIGNATION_ID=@DESIGNATION_ID;
END

EXEC PR_DESIGNATION_SELECTPK 11

CREATE PROC PR_PERSON_SELECTPK
   @WORKER_ID INT
AS
BEGIN
   SELECT * FROM PERSON
   WHERE WORKER_ID=@WORKER_ID;
END

EXEC PR_PERSON_SELECTPK 103

--4.CREATE PROCEDURE THAT TAKES DEPARTMENT NAME ANS DESIGNATION NAME AS INPUT ANS RETURNS A TABLE WITH WORKERS FIRST NAME ,SALARY , JOINING DATE, AND DEPARTMENT NAME

CREATE PROC PR_INPUT
  @DEPARTMENT_NAME  VARCHAR(100),
  @DESIGNATION_NAME VARCHAR(100)
AS
BEGIN
  SELECT P.FIRST_NAME,P.SALARY,P.JOINING_DATE,D.DEPARTMENT_NAME
  FROM PERSON AS P INNER JOIN DEPARTMENT AS D
  ON P.DEPARTMENT_ID=D.DEPARTMENT_ID
  INNER JOIN DESIGNATION AS DE
  ON P.DESIGNATION_ID=DE.DESIGNATION_ID
  WHERE D.DEPARTMENT_NAME=@DEPARTMENT_NAME AND DE.DESIGNATION_NAME=@DESIGNATION_NAME;
END
EXEC PR_INPUT 'HR','CEO'

--5.Create Procedure that takes FirstName as an input parameter and displays’ all the details of the worker with their department & designation name.

CREATE PROC PR_INPUT1
  @FIRST_NAME  VARCHAR(100)
AS 
BEGIN
     SELECT P.WORKER_ID,
	        P.FIRST_NAME,
			P.LAST_NAME,
			P.SALARY,
			P.JOINING_DATE,
			P.DEPARTMENT_ID,
			P.DESIGNATION_ID,
			D.DEPARTMENT_NAME,
			DE.DESIGNATION_NAME
  FROM PERSON AS P INNER JOIN DEPARTMENT AS D
  ON P.DEPARTMENT_ID=D.DEPARTMENT_ID
  INNER JOIN DESIGNATION AS DE
  ON P.DESIGNATION_ID=DE.DESIGNATION_ID
  WHERE P.FIRST_NAME=@FIRST_NAME;
END
EXEC PR_INPUT1 'NEHA'

--6. Create Procedure which displays department wise maximum, minimum & total salaries.

CREATE PROC PR_DISPLAY_SALARY
AS
BEGIN
  SELECT DEPARTMENT_NAME,MAX(P.SALARY) AS MAXIMUM,MIN(P.SALARY) AS MINIMUM,SUM(P.SALARY) AS TOTAL
   FROM DEPARTMENT AS D INNER JOIN PERSON AS P
   ON D.DEPARTMENT_ID=P.DEPARTMENT_ID
   GROUP BY DEPARTMENT_NAME;
END

EXEC PR_DISPLAY_SALARY

--VIEWS--
--1. Create a view that display first 100 workers detailS.
 CREATE VIEW FIRST_100
 AS
  SELECT TOP 100 * FROM PERSON;
SELECT * FROM FIRST_100

--2. Create a view that displays designation wise maximum, minimum & total salaries.
CREATE VIEW DESIGNATION_SALARY
AS
  SELECT D.DESIGNATION_NAME,MAX(P.SALARY) AS MAXIMUM,MIN(P.SALARY) AS MINIMUM,SUM(P.SALARY) AS TOTAL
   FROM DESIGNATION AS D INNER JOIN PERSON AS P
   ON D.DESIGNATION_ID=P.DESIGNATION_ID
   GROUP BY DESIGNATION_NAME;
SELECT * FROM DESIGNATION_SALARY

--3. Create a view that displays Worker’s first name with their salaries & joining date, it also displays duration column which is difference of joining date with respect to current date.

ALTER VIEW DISPLAY_WORKER
AS
  SELECT FIRST_NAME,SALARY,JOINING_DATE,DATEDIFF(YEAR,JOINING_DATE,GETDATE()) AS DURATION 
  FROM PERSON
SELECT * FROM DISPLAY_WORKER

--4. Create a view which shows department & designation wise total number of workers.

CREATE VIEW TOTAL_WORKERS
AS
  SELECT D.DEPARTMENT_NAME,COUNT(P.FIRST_NAME) AS TOTAL
  FROM PERSON AS P INNER JOIN DEPARTMENT AS D
  ON P.DEPARTMENT_ID=D.DEPARTMENT_ID 
  GROUP BY D.DEPARTMENT_NAME;

  SELECT * FROM TOTAL_WORKERS

ALTER VIEW TOTAL_WORKERS_DE
AS
  SELECT DE.DESIGNATION_NAME,COUNT(P.FIRST_NAME) AS TOTAL
  FROM PERSON AS P INNER JOIN DESIGNATION AS DE
  ON P.DESIGNATION_ID=DE.DESIGNATION_ID 
  GROUP BY DE.DESIGNATION_NAME;
    
SELECT * FROM TOTAL_WORKERS_DE

--5. Create a view that displays worker names who don’t have either in any department or designation.

CREATE VIEW WORKER_DETAIL
AS
  SELECT FIRST_NAME
  FROM PERSON
  WHERE DEPARTMENT_ID IS NULL OR DESIGNATION_ID IS NULL;
   SELECT * FROM WORKER_DETAIL